title: Community Chart Components
description: > # this means to ignore newlines in this property's value
  Community Chart Components.

# Build settings

exclude:
  - Gemfile
  - Gemfile.lock

safe: true
